# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "bitcache"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# See: https://readmer.dev
[package.metadata.readmer.project]
title = "Bitcache"
summary = "Bitcache is a distributed content-addressable storage (CAS) system."

[features]
default = ["all", "std"]
all = ["base58"]
alloc = ["bitcache-core/alloc"]
cli = ["std", "tokio", "bitcache-core/clap", "dep:bitcache-fs", "dep:clientele", "dep:clap"]
std = ["alloc", "bitcache-core/std"]
unstable = []

# Features:
base58 = ["bitcache-core/base58"]

# Backends:
fs = ["dep:bitcache-fs"]
heap = ["dep:bitcache-heap"]
iroh = ["dep:bitcache-iroh"]
opendal = ["dep:bitcache-opendal"]

# Interoperability:
serde = ["bitcache-core/serde"]
tokio = ["std", "bitcache-core/tokio", "bitcache-fs?/tokio", "dep:tokio", "tokio/fs", "tokio/io-std", "tokio/io-util", "tokio/macros", "tokio/rt-multi-thread"]

[dependencies]
bitcache-core = { workspace = true }
bitcache-fs = { workspace = true, optional = true }
bitcache-heap = { workspace = true, optional = true }
bitcache-iroh = { workspace = true, optional = true }
bitcache-opendal = { workspace = true, optional = true }

# CLI:
clap = { workspace = true, optional = true }
clientele = { version = "0.3.8", features = [], optional = true }
tokio = { version = "1", default-features = false, optional = true }

[dev-dependencies]
distrib = { version = "0", default-features = false, features = ["alloc"] }

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bin]]
name = "bitcache"
path = "src/main.rs"
required-features = ["cli"]

# See: https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md
[package.metadata.binstall]
disabled-strategies = ["quick-install"]
