# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "bitcache"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# See: https://readmer.dev
[package.metadata.readmer.project]
title = "Bitcache"
summary = "Bitcache is a distributed content-addressable storage (CAS) system."

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["all", "std"]
all = ["auto-register", "base58", "fs", "heap", "valkey"]
alloc = [
    "bitcache-core/alloc",
    "bitcache-fs?/alloc",
    "bitcache-heap?/alloc",
    "bitcache-iroh?/alloc",
    "bitcache-opendal?/alloc",
    "bitcache-valkey?/alloc",
]
std = [
    "alloc",
    "bitcache-core/std",
    "bitcache-fs?/std",
    "bitcache-heap?/std",
    "bitcache-iroh?/std",
    "bitcache-opendal?/std",
    "bitcache-valkey?/std",
    "ctor?/std",
]
unstable = []

# Features:
auto-register = ["dep:ctor"]
base58 = ["bitcache-core/base58"]

# Adapters:
adapters = ["fs", "heap", "iroh", "opendal", "valkey"]
fs = ["dep:bitcache-fs"]
heap = ["dep:bitcache-heap"]
iroh = ["dep:bitcache-iroh"]
opendal = ["dep:bitcache-opendal"]
opendal-all = [
    "opendal-azblob",
    "opendal-fs",
    "opendal-ftp",
    "opendal-gcs",
    "opendal-http",
    "opendal-memcached",
    "opendal-memory",
    "opendal-mongodb",
    #"opendal-redb",
    "opendal-redis",
    #"opendal-rocksdb",
    "opendal-s3",
    "opendal-sftp",
    "opendal-sled",
    #"opendal-sqlite",
]
opendal-azblob = ["opendal", "bitcache-opendal?/azblob"]
opendal-fs = ["opendal", "bitcache-opendal?/fs"]
opendal-ftp = ["opendal", "bitcache-opendal?/ftp"]
opendal-gcs = ["opendal", "bitcache-opendal?/gcs"]
opendal-http = ["opendal", "bitcache-opendal?/http"]
opendal-memcached = ["opendal", "bitcache-opendal?/memcached"]
opendal-memory = ["opendal", "bitcache-opendal?/memory"]
opendal-mongodb = ["opendal", "bitcache-opendal?/mongodb"]
#opendal-redb = ["opendal", "bitcache-opendal?/redb"]
opendal-redis = ["opendal", "bitcache-opendal?/redis"]
#opendal-rocksdb = ["opendal", "bitcache-opendal?/rocksdb"]
opendal-s3 = ["opendal", "bitcache-opendal?/s3"]
opendal-sftp = ["opendal", "bitcache-opendal?/sftp"]
opendal-sled = ["opendal", "bitcache-opendal?/sled"]
#opendal-sqlite = ["opendal", "bitcache-opendal?/sqlite"]
valkey = ["dep:bitcache-valkey"]

# Interoperability:
clientele = ["dep:clientele"]
serde = ["bitcache-core/serde"]
tokio = [
    "std",
    "bitcache-core/tokio",
    "bitcache-fs?/tokio",
    "dep:tokio",
    "tokio/fs",
    "tokio/io-std",
    "tokio/io-util",
    "tokio/macros",
    "tokio/rt-multi-thread",
]

# CLI:
cli = [
    "auto-register",
    "clientele",
    "clientele?/all",
    "clientele?/std",
    "std",
    "tokio",
    "bitcache-core/clap",
    "dep:bitcache-fs",
    "dep:clap",
    "dep:color-print",
]

[dependencies]
bitcache-core = { workspace = true }
bitcache-fs = { workspace = true, optional = true }
bitcache-heap = { workspace = true, optional = true }
bitcache-iroh = { workspace = true, optional = true }
bitcache-opendal = { workspace = true, optional = true }
bitcache-valkey = { workspace = true, optional = true }
thiserror = { workspace = true }

# Features:
ctor = { version = "1.0", default-features = false, features = ["proc_macro"], optional = true }

# CLI:
clap = { workspace = true, optional = true }
clientele = { workspace = true, optional = true }
color-print = { version = "=0.3.7", optional = true }
tokio = { workspace = true, optional = true, features = ["fs"] }

[dev-dependencies]
distrib = { version = "0", default-features = false, features = ["alloc"] }

[[bin]]
name = "bitcache"
path = "src/main.rs"
required-features = ["cli"]

# See: https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md
[package.metadata.binstall]
disabled-strategies = ["quick-install"]
