# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "bitcache-git"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["all", "std"]
all = []
alloc = ["bitcache-core/alloc"]
std = ["alloc", "bitcache-core/std"]
unstable = []

[dependencies]
bitcache-core = { workspace = true, features = [] }
gix = { workspace = true, features = [] }
