# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "0.0.1"
authors = ["Arto Bendiken"]
edition = "2024"
rust-version = "1.88"
description = "Bitcache is a distributed content-addressable storage (CAS) system."
#documentation = "https://docs.rs/bitcache"
readme = true
homepage = "https://bitcache.dev"
repository = "https://github.com/artob/bitcache"
license = "Unlicense"
keywords = ["bitcache", "content-addressed", "content-addressable", "content-addressing"]
categories = ["command-line-utilities", "caching", "filesystem"]
publish = true

[workspace]
members = ["lib/*"]
resolver = "2"

[workspace.dependencies]
bitcache = { version = "=0.0.1", default-features = false }
bitcache-core = { version = "=0.0.1", default-features = false }
bitcache-fs = { version = "=0.0.1", default-features = false }
bitcache-heap = { version = "=0.0.1", default-features = false }
bitcache-iroh = { version = "=0.0.1", default-features = false }
bitcache-opendal = { version = "=0.0.1", default-features = false }

[patch.crates-io]
bitcache = { path = "lib/bitcache" }
bitcache-core = { path = "lib/bitcache-core" }
bitcache-fs = { path = "lib/bitcache-fs" }
bitcache-heap = { path = "lib/bitcache-heap" }
bitcache-iroh = { path = "lib/bitcache-iroh" }
bitcache-opendal = { path = "lib/bitcache-opendal" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
