# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "bitcache-opendal"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = ["all", "std"]
all = []
alloc = []
std = ["alloc"]
unstable = []

[dependencies]
opendal = { version = "0.58", default-features = false }
